title: Interest Rate Modeling
description: Companion website for books by L. Andersen and V. Piterbarg
theme: jekyll-theme-tactile
#theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - ISSUE_TEMPLATE.md
